version: "3"
services:
    app:
        image: golang:1.12.17
        volumes:
        - .:/app/
        working_dir: /app/
        command: go run . --port 8000 --config './data/config.json'
        ports:
            - "80:8000"
